name: Release
on:
  push:
    branches: ["master", "beta"]
    paths-ignore:
      - ".husky/**"
      - "**.md"
      - package.json
permissions:
  contents: write # to be able to publish a GitHub release

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn
      
      - name: Build
        run: yarn build # Outputs to dist/

  build-proxy:
    name: Build Proxy
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: src-proxy

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: |
          cargo build --release
          ls -l target/release

  # release:
  #   name: Release
  #   needs: [build-extension]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #         persist-credentials: false

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20.x
  #         cache: "yarn"

  #     - name: Install dependencies
  #       run: yarn add -D semantic-release @semantic-release/changelog @semantic-release/git

  #     - name: Release
  #       run:
  #         yarn semantic-release
  